### ISSUE TITLE
Suggest using SQLAlchemy for database abstraction

### ISSUE THREAD

**Issue by Berserkir-Wolf** [Casvt/Kapowarr#101]
**Is your feature request related to a problem? Please describe.**
SQLite does not handle multi-threaded input well. Database locks become common with larger tasks.

**Describe the solution you'd like**
Switching 'from pure' SQL by adding an abstraction layer will allow for slightly better handling of queuing, while simultaneously adding support for alternate databases (like MySQL or MariaDB). A default DB can be set to auto-deploy, so that for new users setup is easy.

**Additional suggestion**
In the case of existing users who outgrow SQLite (which will happen with larger databases - there's no avoiding that, really), we could add a function in the UI to migrate to new DB and set the connection details in a config file. 
Something like fields for:

- DB type
- DB host
- DB Name
- DB username
- DB password

Include buttons for:
- Test
  Validates login details and DB access
- Submit
  Saves the details and puts them into the config file for loading on startup next time
- Migrate
  Copies the data from the SQLite database to the new MySQL/MariaDB database

On next restart of Kapowarr, it can use the new DB (with all the perks of full SQL). 
Alternately, it could do the migration on startup if target DB = empty and SQLite DB is present, then rename the sqlite DB to something like 'Kapowarr_archived.db'

**Comment by Casvt** [comment]
My personal preference is against ORM's like SQLAlchemy. You have less control over how the "code" is turned into SQL. The commands that I use are optimised for the database structure of Kapowarr and for bigger tasks multiple versions of the same command are tested to find the fastest/most efficient one. When using an ORM, I feel like I loose too much of this control. It also makes the code slower (calling all the functions, creating class instances, loads of processing to build the query).

You suggest that people will grow out of the SQLite DB. I don't think so; these days SQLite can easily handle millions of rows (and the only table that will grow to anywhere near that size would be the issues table). So then also no need to allow/support other databases.

So I'd rather keep using direct SQL. The only thing that _is_ good about using an ORM like SQLAlchemy is that it indeed has better support for making the synchronous database look like an asynchronous one. But I'm not going to change hundreds of lines of code to switch to SQLAlchemy purely for that advantage. I'd rather just look at the source code for how they have implemented this feature and just see if I can copy that over (or take inspiration from it). I've been working on reducing the 'database locked' error and as far as I know these days they rarely pop up anymore.

Radarr/Sonarr also just use an SQLite database.

----

I'm going to close the issue, but I do get the message and I will work some extra to see what I can do to improve how Kapowarr uses the database.
