### ISSUE TITLE
###.WORD Issues not being found

### ISSUE THREAD

**Issue by Auram** [Casvt/Kapowarr#104]
<img width="1072" alt="image" src="https://github.com/Casvt/Kapowarr/assets/7597586/2b76fa7d-fae7-410b-8a9d-160a30a172cb">

This screenshot is from Spencer's Amazing Spider-Man (2018). Occasionally comics do this dumb thing where an issue number will be followed by a . and some kind of word delineation. Like #92 and #92.BEY both exist, but Kapowarr has trouble finding and adding #92.BEY without manual intervention.

<img width="259" alt="image" src="https://github.com/Casvt/Kapowarr/assets/7597586/2144959e-c804-4719-8d71-4ac46c167949">
Running on unRAID in a Docker container.

**Comment by Casvt** [comment]
Weird notation indeed but I can add support for it sure :)

**Comment by Casvt** [comment]
Required two characters to be added and one to be changed so that was probably the quickest fix I've ever done.

Fix will be included in next alpha release and next beta release.
