### ISSUE TITLE
Improvements to the Add Volume section

### ISSUE THREAD

**Issue by Auram** [Casvt/Kapowarr#105]
The Add Volume section could use some improvements to get accurate results and speed up the post-add process.

First thing would be more filters using some of the already existing tags that ComicVine exposes. This would help to eliminate redundant results and quickly find what you're actually looking for.
- Publisher
- Number of issues
- TPB/Ongoing/Ended/Etc
- Sort by (release date, name, previous filters)

Then once you've found what you want, an "Add + Search" button in addition to the existing "Add" button would be really great if you just want to immediately find and download the comics. This could get hairy with giant volumes since Kapowarr's queue gets gunked up with too many issues at once, but for small volumes it'd be a great QOL thing.

**Comment by Casvt** [comment]
All sounds good. One note though:

> Ongoing/Ended/Etc

CV doesn't supply info about whether or not a volume is still running or not. So I can't filter by that, but that's the only problem.

**Comment by Auram** [comment]
Huh, interesting. Seems like an oversight on their end. I wonder if you could hack a way to determine ongoing status by how far away from the current date the last release was? So like if Spider-Man Vol 8 #20 came out six months ago and there hasn't been a #21, its safe to say that book is over.

**Comment by Casvt** [comment]
![image](https://github.com/Casvt/Kapowarr/assets/88994465/9104df22-9c26-4ea1-be25-bedd071cadcf)
It's hard to determine in situations like the one in the picture. You could assume that after the release in 2000 it's ended but then suddenly 6 years later there is a new issue. So was it really ended then?

I could say that *Kapowarr* (and not *CV*) considers volumes as ended when the last issue was >6 months ago. But it won't be a guarantee that it has actually ended. There could very well be a new issue 6 years later. But the users can also just accept the fact that Kapowarr has to make that assumption.

**Comment by Auram** [comment]
Ugh, yeah good point. Comics are so confusing sometimes lol
Something that can be configured from user preference perhaps?

**Comment by Casvt** [comment]
It's merely what Kapowarr uses as the threshold for when a volume in the search results is considered ended. I don't think that needs to be an option (too niche), the user will just have to live with what Kapowarr thinks. At most I could turn the filter from 'Ongoing' in to 'Last issue released within last \<input\> months', but that will depend on my mood on the day I'm implementing this to spend (maybe _considerable_) time on a very niche feature (compared to just accepting the 6 month constant).

**Comment by Casvt** [comment]
Forgot to put issue number in commit, but commit 209acc2178854d5fde0e3b758f56aeee85a8b74d implements the 'Search on add' feature. Only thing left is filtering based on ongoing/ended.

**Comment by Casvt** [comment]
When searching for volumes, there is a key which gives information about the last issue of the volume. It gives the link to the issue, it's ID, it's issue number, _but not the date_. That means that unless I make double the amount of requests per search term, we won't know when the last issue was released and thus if it was 6 months ago. So we can't (in a efficient way) implement the ongoing/ended filter. That was the last thing left so this issue is completed.
