### ISSUE TITLE
Non-standard Issue number

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [Casvt/Kapowarr#106]
**Description of the bug**
When you add The Flash (1987) Volume 2, the issue number between 218 and 219 is ½. This doesn't map to the file properly.

**Expected behaviour**
Either resolve issue number to 1/2 and map to file OR fix detection. Even better would be an option to do a Manual Import.

**Screenshots**
![Screenshot from 2023-11-26 13-31-59](https://github.com/Casvt/Kapowarr/assets/98815412/50327b00-d99f-4f7a-86b4-7a0e6d895e39)

**Version info**
Kapowarr version 	v1.0.0-beta-3
Python version 	3.8.17.final.0
Database version 	10
Database location 	/app/db/Kapowarr.db
Data folder 	/app

**Comment by Casvt** [comment]
The 1/2 character is already supported by Kapowarr. What is the filename?

**Comment by Gandalf-the-Blue** [comment]
The Flash 1987 Volume 2 Issue ½

**Comment by Casvt** [comment]
Looks like Kapowarr incorrectly extracts data from the filename, making it not match. It's strange because it should work already but I'll fix it.

**Comment by Casvt** [comment]
That's pretty much impossible to handle automatically. And I'm not going to. Scenarios such as these are better handled by the planned "Manual File Matching" feature (#46)
