### ISSUE TITLE
[Bug] New books being added as TBP

### ISSUE THREAD

**Issue by JaredVanderford** [Casvt/Kapowarr#108]
**Description of the bug**
The logic for determining if a volume is TPB appears to just be if the issue count = 1.  While this likely works for older books, as new volumes are released and added, the volume is being flagged as a TPB when it's a normal ongoing series.  The volume info is not updating as more issues are released, and because the volume is flagged as a TPB it is not matching issues correctly on the auto search.

**To Reproduce**
1.  Go to 'Add volume'
2.  Search for a new series (as of this date Spider-Woman has a new volume)
3.  Add volume with only 1 current issue.
4.  Go to home page.
5.  Navigate to newly added volume, see it is flagged as TPB
6.  Wait till more issues are released
7.  When more issues are released, see that the TPB special issue flag is not removed from the volume.
8.  Manually search for new issue.
9.  See match failure due to special version conflict.

**Expected behaviour**
Either not flagging new ongoing series as TPB, or if that is unavoidable due to lack of metadata, when new issues are added to the volume, remove the TPB flag to allow for issue matching.

**Screenshots**
![TPB screenshot 2](https://github.com/Casvt/Kapowarr/assets/2420694/6d828518-9ae8-48cc-b778-98c17abd5c5f)
![TPB screenshot 1](https://github.com/Casvt/Kapowarr/assets/2420694/f4ad6ab3-807c-4d89-a977-e72638a7e91a)

**Version info**
Kapowarr version   v1.0.0-beta-3
Python version 3.8.17.final.0
database version 10
Windows 11 Pro
Hosted on Docker
Brave Version 1.60.118 

**Additional context**
Looking at the dev branch, the logic for setting TPB is in volumens.py lines 66-67

**Comment by Casvt** [comment]
Fixed in commit c2a946632e48014a3796c6e731367f1895af8af1
