### ISSUE TITLE
Override special version state

### ISSUE THREAD

**Issue by JaredVanderford** [Casvt/Kapowarr#109]
**Description of the bug**
The volume file scanner seems to be unable to find my issues on ongoing series that are currently flagged as TPB.  For any ongoing series I have in my library that is currently flagged as a TPB (only 1 issue) none of the issues are found when scanning.  The library import tool is able to find them just fine, and trying to import them does import the volume correctly, but still doesn't show the issues as being present.

**To Reproduce**
1. Go to Library Import
2. Import a series that only has 1 issue in release (Carnage (2023) as of this week).
3. Go to home page, verify that volume is imported but no issues show as found (but issues are showing as monitored).

**Expected behaviour**
I'd expect it to find the issues for the volume and mark them as found for monitored issues.  I suspect this is due to them being flagged as TPB, only consistency I could find between the various volumes that have this is that they are all ongoing series with 1 issue so flagged as TPB by Kapowarr.  Ideally it would just detect the issue, but I imagine the problem is due to name expected to have TPB and they don't.  Since I don't think there's good metadata to determine a TPB vs ongoing series, perhaps just adding that checkbox at volume add for volumes with only one series to flag as ongoing rather than TPB to avoid these conflicts would solve the problem.

**Screenshots**
![Missing Issues TPB](https://github.com/Casvt/Kapowarr/assets/2420694/79b619f3-4d41-4e87-865f-f0d988bfcfd3)
![Missing Issues TPB 2](https://github.com/Casvt/Kapowarr/assets/2420694/cd540018-9cbc-48d7-a9f1-672abac148d8)

**Version info**
Kapowarr version	v1.0.0-beta-3
Python version	3.8.17.final.0
Database version	13
OS                            Windows 11 Pro
Browser                    Brave Version 1.60.118 

**Additional context**
This issue was not present prior to me swapping to the dev docker image, so it was introduced since the last full release.

**Comment by JaredVanderford** [comment]
I get all the logic around 1 issue = TPB, my point is that the simplified logic causes issues for new ongoing series until a 2nd issue is out.  It won't grab issues automatically because they don't match as needed, it won't flag them as in the collection so looking at the collection page is misleading if the user isn't paying attention to the issue count, and the waiting a month seems to be counter productive to a tool like this that monitors these volumes so actively.  I understand that computing if a volume is a TPB is not easy given the lack of metadata from CV, but the current assumption is problematic in a different way.  Having a way to override the computed value for TPB and set it manually would solve this given the logic for computing if its a TPB volume is unreliable.  Waiting a month (or more) for it to fix itself feels like not the right solution IMO.   That said it's your work and I understand if what I'm asking for is out of scope or unreasonably complex for the existing code base.

**Comment by Casvt** [comment]
Oh no I can add it, that's not the problem. I just meant that it's an inconvenience sure, but not truly breaking Kapowarr right now so it's less high on the list.

**Comment by JaredVanderford** [comment]
Given that it is now not working to manually search and download due to this issue, does this move from an inconvenience to something breaking Kapowarr?  I had created the other issue thinking the 2 could be fixed differently but given you closed #136 i suppose you think they are inseperable?

**Comment by JaredVanderford** [comment]
I'd also add that the manual download used to work, but no longer does.  Hence the new issue.  This was an inconvenience in that it didn't show collection correctly or auto grab, but now the manual search and download workaround no longer works.

**Comment by Casvt** [comment]
#136 is a result of this problem. If I fix this, all errors/inconsistenties that follow from this will fix themselves too. So yes, if I fix this, the other issue will be fixed automatically (which makes me consider it the same bug/issue).

To say it in a different way: what you're experiencing is correct behaviour for a TPB, only is the volume not a TPB. So we should fix that the volume is considered a TPB, and that is what this issue is about.

When you reported this issue, manual search was already broken, you've just noticed only now.

Currently, you can not download the first issue until the second issue releases. So it fixes itself eventually, but I understand the inconvenience and I have planned to fix this before the stable release.

**Comment by Casvt** [comment]
It's not _that_ hard to implement, so no worries. You'll have it in one of the next alpha releases, and for sure in the stable release.

**Comment by JaredVanderford** [comment]
Minor update for anyone else who sees this issue.  Until the full fix is out and available, you can update the volume special version via API ("/volumes/$id") route simply passing in `"special_version": null` as a field.  It will persist through the overall server update call, but if you use the refresh and scan option on the volume page it does revert to a TPB version
