### ISSUE TITLE
Comic issue not recognized when the title contains "Chapter #"

### ISSUE THREAD

**Issue by kclimie** [Casvt/Kapowarr#110]
**Description of the bug**
When the title of a comic issue contains "Chapter #", the scanner uses the chapter number as the issue number rather than the actual issue number from the filename. The issue is marked as missing rather than complete.

**To Reproduce**
1. Add "The Mandalorian, Vol2 (2023)" to the library
2. Add file to comic directory
example: 'Star Wars The Mandalorian (2023) - v02 - Issue 001 - Chapter 9 Redemption.cbz'

3. From the GUI, click the Refresh & Scan button
4. Debug output is: 
[Task Handler][DEBUG] Extracting filename data: /comics/Star Wars The Mandalorian/Volume 02 (2023)/Star Wars The Mandalorian (2023) - v02 - **Issue 001** - Chapter 9 Redemption.cbz
[Task Handler][DEBUG] Extracting filename data: {'series': 'Star Wars The Mandalorian', 'year': 2023, 'volume_number': 2, 'special_version': None, **'issue_number': 9.0**, 'annual': False}

5. If you use remove the "Chapter 9" from the filename, the correct issue number is used and the issue marked as complete. However, if the system renames the file using the issue title, "Chapter 9" is added back into the filename and the issue is subsequently re-marked as missing.

**Expected behaviour**
The name scanner should use the "Issue #" as the issue number rather than the "Chapter #" and mark the issue as complete.

**Version info**
About

Kapowarr version	v1.0.0-beta-3
Python version	3.8.17.final.0
Database version	10
Database location	/app/db/Kapowarr.db
Data folder	/app

Kapowarr is running in a Docker container on Ubuntu 22.04.
Client is MacOS 14.1.1, using Safari 17.1. Issue persists regardless of client/browser combination.

**Comment by Casvt** [comment]
Already fixed. Will be included in the next release.

```python
>>> print(dumps(ef('/comics/Star Wars The Mandalorian/Volume 02 (2023)/Star Wars The Mandalorian (2023) - v02 - Issue 001 - Chapter 9 Redemption.cbz'), indent=4))
{
    "series": "Star Wars The Mandalorian",
    "year": 2023,
    "volume_number": 2,
    "special_version": null,
    "issue_number": 1.0,
    "annual": false
}
```
