### ISSUE TITLE
Root folder?

### ISSUE THREAD

**Issue by delaho** [Casvt/Kapowarr#111]
MacOS, Docker container running Kapowarr, I have made sure Docker has access to file sharing in resources. No matter what I type in here I get "Folder doesnt exist". Ideas? ideally I want the root folder to be the SMB share my Mac already has access to in Volumes.
![image](https://github.com/Casvt/Kapowarr/assets/153228612/af5e3cb1-7c94-4e4c-8018-32f83745243c)

**Comment by Casvt** [comment]
Well open a shell in the container and run `ls /` to see if you see the folder in the list.

If not, you're doing something wrong in the docker command at `-v`.

If you do, check the permissions.

**Comment by delaho** [comment]
I did manage to add the volume in the UI. But I started messing with the command line first. I appreciate the assist regardless.
