### ISSUE TITLE
docker image in DockerHub has no exposed ports

### ISSUE THREAD

**Issue by elblanco5** [Casvt/Kapowarr#119]
**Description of the bug**
(sorry kind of a n00b here). I use Docker Desktop on Windows to help make dockering easier since I'm not super technical and I've found it pretty easy to set up a decent system for myself. I've pulled the other *arr images from linuxserver/*arr and they all expose a port I can map when starting the image. However, the mrcas/kapowarr image doesn't have any exposed ports. 

**To Reproduce**
1. Get the latest mrcas/kapowarr image from dockerhub using docker desktop.
2. Start the image
3. Select "Optional settings" in the docker desktop GUI
4. Under Ports it says "No ports exposed in this image"

**Expected behaviour**
I think it would be helpful if the image worked like the linuxserver/*arr images and already had a port exposed that could be mapped to.

**Version info**
The version that's presently on dockerhub (about 7 months old).

**Comment by Casvt** [comment]
Yeah I know next release will have it

**Comment by elblanco5** [comment]
Cool thanks! I wasn't expecting any response today! Have a great New Years!
