### ISSUE TITLE
Manga Support

### ISSUE THREAD

**Issue by TorchedSammy** [Casvt/Kapowarr#123]
**Is your feature request related to a problem? Please describe.**
As it seems that kapowarr uses Comic Vine for metadata, I think a definitive source for manga should be added. Comic Vine is not that good for manga, especially if it's (un)officially translated to English or any other language.

**Describe the solution you'd like**
Using a better source of metadata for manga, like [MangaUpdates](https://mangaupdates.com) or MyAnimeList. I'm not sure of any ideas on how you would add this, considering if a user wants to search for a manga and both sources are used there could be duplicates. Maybe a toggle for metadata source?

Also, there are multiple sites one could get manga from. I'll say what I think about each:
- **MangaUpdates**: Definitely the best source for info on manga, I'm not sure how the API for fetching info is (but there is an official one). Everything is gonna be here.
- **MyAnimeList**: Possibly more straightforward, otherwise just an alternative source. Likely missing some niche manga that is on MangaUpdates.
- **AniList**: Alternative source, would have less than MAL but also have stuff not on MAL.

**Additional context**
Unrelated to #73

**Comment by Casvt** [comment]
No supporting manga is wayyy to complicated. Manga could and should be a whole seperate application.
