### ISSUE TITLE
Clicking on the Kapowarr icon should take you to the Volumes display (instead of doing nothing)

### ISSUE THREAD

**Issue by YodaDaCoda** [Casvt/Kapowarr#128]
Kapowarr fits nicely into the *arr suite of applications. When I use the other *arrs, whenever I want to go back to the 'home' of the application, I just click the app's icon in the header. This doesn't work with kapowarr; i think it should.

Happy to raise a PR for this, just give me a couple days to get around to it.

**Comment by Casvt** [comment]
Sure go for it
