### ISSUE TITLE
Can't save General Settings

### ISSUE THREAD

**Issue by Zaliyep** [Casvt/Kapowarr#137]
**Description of the bug**

Trying to add a ComicVine API key to General Settings, but the save button doesn't do anything. I've tried this on Brave (Chromium), Chrome, Edge, and Firefox and continue to have the same issue.

**To Reproduce**

Try to add ComicVine API key and click 'save'.

**Expected behaviour**

I expected the ComicVine API key to save, but it disappears when I leave the page and return.

**Version info**

System: TrueNAS Scale
Name: kapowarr
App Version: 1.0.0
Chart Version: 2.0.3

**Comment by zehro** [comment]
@Zaliyep Did you find a solution? I'm encountering a similar error on TrueNAS Scale

**Comment by Casvt** [comment]
Could be multiple things:

1. Remove any spaces before and especially after the value, i.e. `abc` and not `abc `.
2. The api key is incorrect/invalid/blocked. That's unlikely though.
3. Check the logs for any errors and share them if you find any.
