### ISSUE TITLE
Can't get series issues to match.

### ISSUE THREAD

**Issue by battousaifader** [Casvt/Kapowarr#140]
Problem matching issues with Deathstroke (2016) Volume 4. Its a 50 issue series, but after adding the series, under the title, its listed as a "ONE-SHOT" which I think is the cause of the problem. I'm not able to make any of the issues match except the first one, if I append "ONE-SHOT" to the name, but If I try and use the "Preview Rename" button, it removes the Issue number from the name.

Add Deathstroke (2016) Volume 4, try matching comics.

1. Go to add Volume: 
2. Add Deathstroke (2016) Volume 4
3. try matching comics with "refresh & scan"

**Expected behaviour**

For the issues to be matched.

**Version info**

Kapowarr version 	v1.0.0-beta-4

Docker version on Linux running on server computer
Windows 11, Firefox browser Client

**Additional context**

Not sure what would be the best fix for this, maybe the ability to manually override if series are considered One-Shots, TPB's, Normal Series, etc... That would work if the problem is indeed caused by the series metadata from the server.

**Comment by Casvt** [comment]
Evaluation of the volume for whether or not it's an one-shot is done by Kapowarr, not by CV. I'll check why Kapowarr is wrongly considering this specific volume to be an one-shot.

For other purposes, overriding the special state is already planned in #109.
