### ISSUE TITLE
Problem searching for comic with many special characters and a slash in its series title

### ISSUE THREAD

**Issue by hotcereal** [Casvt/Kapowarr#147]
_**Description of the bug**_

The only comic that I can immediately test with is "Batman/Superman: World’s Finest (2022)"

Searching for any issue results in empty results, but manually placing the comic in its respective folder does allow it to be matched if named properly. 

For ongoing series, it presents a problem wherein users will have to manually track and download comics as they come out. For older comics, manually importing the comic is a one-time ordeal; much less frustrating. It is worth noting that the comic is available via GC and the links appear to be bountiful for each issue. 

_**To Reproduce**_

1. Go to '_Add Volume_'.
2. Search for "**Batman/Superman: World’s Finest (2022)**" and '_Add Volume_'.
3. Click on '_Search Monitored_' or manually search by clicking the human glyph icon.
4.  Should result in no results, an empty list.

_**Expected behaviour**_

See results, download them, have them mapped/matched.

_**Screenshots**_

<img width="1920" alt="Screenshot 2024-04-03 at 9 03 40 AM" src="https://github.com/Casvt/Kapowarr/assets/7705074/fcd2fc20-aa4e-4aa5-a753-3b5ae4f1604b">

_**Version info**_

**Kapowarr version**:	v1.0.0-beta-4
**Python version**:	3.8.17.final.0
**Database version**:	14

_**Additional context**_

This is the only comic that has this specific issue. I can't seem to figure out what it could be, but my leading hunch is that it may be that the slash is directlly between two letters the same way a file directory would be. Making me believe the cause may be that Kapowarr is looking for a directory (to some extent) as opposed to the comic itself. 

If it's not that, my only guess can be the abundance of special characters. The name of the series has 2 ( / and -)  and a lot of the titles feature a semicolon. However, the semicolons in issue titles is relatively common.

**Comment by hotcereal** [comment]
Would the problem that caused this also be the source of the problem that makes issues unmatch when their file name has numbers at the beginning or ones that don't pertain to the issue or volume?

For example:

**The Wicked + The Divine (2014) - 001 Once Again - [2014-06-30].cbr** will work fine with little to no issue. However, if the files name were to be **001 Once Again - The Wicked + The Divine (2014) - [2014-06-30].cbr** then a new scan will make it unmatch. 

The same issue can be found with titles like **The Wicked + The Divine (2014) - 035 1-2-3-4! ; The Curse in My Hands - [2018-04-30]** but removing the **1-2-3-4** will make it match perfectly fine.

**Comment by Casvt** [comment]
To start with, these are all unrelated problems. The search issue did not have to do with Kapowarr thinking it's a folder. Matching files to volumes is not related too. But that isn't a problem.

Kapowarr matches files with an algorithm that uses patterns to extract data from the filename. Based on this data, it checks if the file is a match and for which issue. The algorithm is not working completely correct with these filenames for various reasons.

- The filename `The Wicked + The Divine (2014) - 001 Once Again - [2014-06-30].cbr` works fine:
```python
{
    "series": "The Wicked The Divine",
    "year": 2014,
    "volume_number": 1,
    "special_version": null,
    "issue_number": 1.0,
    "annual": false
}
```
- The filename `001 Once Again - The Wicked + The Divine (2014) - [2014-06-30].cbr` does not work, and I agree with that. Here, `001 Once Again` means issue `1` and issue title `Once Again`. But how could we differentiate that from `100 Bullets Volume 2 Issue 3`, where the volume is called `100 Bullets`? We can fix it by explicitly stating that the next number is the issue number. See below:
```python
# BAD: 001 Once Again - The Wicked + The Divine (2014) - [2014-06-30].cbr
{
    "series": "001 Once Again The Wicked The Divine",
    "year": 2014,
    "volume_number": 1,
    "special_version": "tpb",
    "issue_number": null,
    "annual": false
}
# GOOD: Issue 001 Once Again - The Wicked + The Divine (2014) - [2014-06-30].cbr
{
    "series": "", # Series name after issue number is not supported; it'll be extracted from the folder name
    "year": 2014,
    "volume_number": 1,
    "special_version": null,
    "issue_number": 1.0,
    "annual": false
}
```
- The filename `The Wicked + The Divine (2014) - 035 1-2-3-4! ; The Curse in My Hands - [2018-04-30]` doesn't work because the algorithm thinks that the issue title is the issue range (it thinks the file covers the issues `-3` to `4`). It is most likely that I can not fix this (without breaking other stuff), but I'll at least try and will get back to you either way.
```python
{
    "series": "The Wicked The Divine",
    "year": 2014,
    "volume_number": 1,
    "special_version": null,
    "issue_number": [
        -3.0,
        4.0
    ],
    "annual": false
}
```

**Comment by hotcereal** [comment]
Insanely useful information, thank you.

**Comment by Casvt** [comment]
Okay I checked the code and tested stuff out.

Firstly, I advised to add 'Issue' to the start to specifically signify that the number is the issue number. Reading the code, I got reminded of an alternative that I had added support for, which is adding a dash:
```python
# BAD: 001 Once Again - The Wicked + The Divine (2014) - [2014-06-30].cbr
{
    "series": "001 Once Again The Wicked The Divine",
    "year": 2014,
    "volume_number": 1,
    "special_version": "tpb",
    "issue_number": null,
    "annual": false
}
# GOOD: Issue 001 Once Again - The Wicked + The Divine (2014) - [2014-06-30].cbr
{
    "series": "", # Series name after issue number is not supported; it'll be extracted from the folder name
    "year": 2014,
    "volume_number": 1,
    "special_version": null,
    "issue_number": 1.0,
    "annual": false
}
# ALSO GOOD: 001 - Once Again - The Wicked + The Divine (2014) - [2014-06-30].cbr
{
    "series": "", # Series name after issue number is not supported; it'll be extracted from the folder name
    "year": 2014,
    "volume_number": 1,
    "special_version": null,
    "issue_number": 1.0,
    "annual": false
}
```

Secondly we have the `1-2-3-4` issue title messing up the algorithm. I managed to fix the algorithm without breaking anything else (which is a small miracle):
```python
# The Wicked + The Divine (2014) - 035 1-2-3-4! ; The Curse in My Hands - [2018-04-30]
{
    "series": "The Wicked The Divine",
    "year": 2014,
    "volume_number": 1,
    "special_version": null,
    "issue_number": 35.0,
    "annual": false
}
```

This fix will be available in the next release.

**Comment by hotcereal** [comment]
Thanks for this, I genuinely appreciate it. It'll definitely help me organize my files in a more cohesive way going forward.
