### ISSUE TITLE
Ability to write tags to issues

### ISSUE THREAD

**Issue by PhAzE-Variance** [Casvt/Kapowarr#150]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to tag all issues and volumes with comictagger info directly into the zip/rar files.

**Describe the solution you'd like**
I would like to be able to auto tag issues with comictagger info, and also have the ability to edit each on a per issue level manually. When saving, it would update the tag info in the file directly.  This will help to maintain the file metadata and replace it entirely if needed, so these files can work more efficiently with readers that rely on metadata to organize the issues, volumes, series, etc.

**Additional context**
N/A

**Comment by Casvt** [comment]
Duplicate of #50 ?

**Comment by PhAzE-Variance** [comment]
I missed that, it is a dupe of 50, so I'll close this.
