### ISSUE TITLE
Title on get comics replaced / with – and it doesn't get found

### ISSUE THREAD

**Issue by Zecrim** [Casvt/Kapowarr#162]
**Description of the bug**

Batman/Superman: World’s Finest failed to download

**To Reproduce**

Try to download Batman/Superman: World’s Finest from getcomics

**Expected behaviour**

Batman/Superman: World’s Finest downloads successfully 

**Version info**

Kapowarr version v1.0.0-beta-4
Python version 3.8.17.final.0
Database version 14
Windows 10, Chrome, Docker

**Additional context**

I think it doesn't get recognized because getcomics styles the title as Batman – Superman – World’s Finest and kapowarr doesn't see the / as –.

**Comment by Casvt** [comment]
Already fixed
