### ISSUE TITLE
Cannot Find Popular Comic

### ISSUE THREAD

**Issue by pjgreen88** [Casvt/Kapowarr#163]
I just started using this service, and although it's serving my purposes pretty well-- I am having one concern that may be a bigger issue once I start adding a bunch of titles.

Currently, trying to add TMNT: The Last Ronin and have it search GetComics to find either the TPB or the issues (tried adding both), but manual search or automatic shows no results. I can find the comic on the website itself, so unsure how to resolve this issue. Thanks for any info you guys can provide.

**Comment by Casvt** [comment]
The title of the volume on CV is `TMNT: The Last Ronin` but on GetComics the releases are titled `Teenage Mutant Ninja Turtles – The Last Ronin`. The `TMNT` and `Teenage Mutant Ninja Turtles` don't match and searching for the first one won't give results of the second.

Kapowarr can't do much about this. In my opinion, this is wrong from CV, where the volume should not be using the abbreviation and should thus be renamed to `Teenage Mutant Ninja Turtles: The Last Ronin`.
