### ISSUE TITLE
LI: Imported files not filtered out on Windows

### ISSUE THREAD

**Issue by dangioffre** [Casvt/Kapowarr#167]
I installed Kapowarr. I was using Mylar.

I have a decent-sized library that needs to be imported into Kapowarr. I am only doing the import by 5 because of API limit. 

I ran in import of 5. It showed me 5 comics. It loaded. It imported. I waited about 30 minutes or so before trying a new import but when I do a new import. It shows me the same 5 comics I already imported.

Kapowarr version | v1.0.0-beta-4

Logs:

[2024-07-18 14:13:45][waitress-4][INFO] Loading library import
[2024-07-18 14:14:04][waitress-4][INFO] Starting library import
[2024-07-18 14:14:04][waitress-4][WARNING] Volume is already added
[2024-07-18 14:14:04][waitress-4][WARNING] Volume is already added
[2024-07-18 14:14:04][waitress-4][WARNING] Volume is already added
[2024-07-18 14:14:04][waitress-4][WARNING] Volume is already added
[2024-07-18 14:14:04][waitress-4][WARNING] Volume is already added
[2024-07-18 14:14:04][waitress-4][WARNING] Volume is already added
[2024-07-18 14:14:04][waitress-4][WARNING] Volume is already added
[2024-07-18 14:14:04][waitress-4][WARNING] Volume is already added

**Comment by Casvt** [comment]
The files are for a volume that is already in your library. However, the files haven't matched to the volume in your library. They're not matched, so they pop up in Library Import. What are the filenames and what is the volume (that is already in your library) that they are for?

**Comment by dangioffre** [comment]
Thanks for the reply.

So I had a folder that has 100s of series but that was when I was using Mylar. So of those series are still active and releasing. I just installed Kapowarr a few hours a go and I wanted to import those comics into Kapowarr. So I went to Volume -> Library Import. I told it to Scan 5 folders to add into volumes and it worked. So I went to add more comics from my folder into Kapowarr volume but it only shows me the 5 folders I just did. Example: "A Hunted girl" 
![image](https://github.com/user-attachments/assets/ad22f35f-749a-4dd6-9b19-6b92e53285a2)
 which I already imported is in my library but if I go to import more comics. It shows me the same one again. 
![image](https://github.com/user-attachments/assets/6f29365e-5f95-428a-81f6-b7794aa40e61)

My Folder:
![image](https://github.com/user-attachments/assets/8ffc43fb-6a3e-4328-a953-378a12137080)

**Comment by Casvt** [comment]
Ah you've reproduced a bug that was 'lost'. A few months ago, a few people encountered this too, I was unable to reproduce it, but they also wouldn't respond when I asked for extra information.

It happens only when running directly on Windows. The file path of the file doesn't match up with the file path registered in the database, even though they refer to the same file.

If you feel comfortable doing so, could you share your database file with me via Discord DM? The information stored inside should be sufficient for finally figuring out what is happening, but if I need more information I'll message you here again of course.

**Comment by dangioffre** [comment]
We are not on windows. We are on a QNAP using docker.

I just mapped my PC to the QNAP so I can easily look at files.

I can touch base with you on Discord tho.

**Comment by Casvt** [comment]
Hmm that's interesting. Up to now, the people encountering this were always directly on Windows. Please DM me your database on discord and we can troubleshoot further there.

**Comment by Casvt** [comment]
dangioffre started fresh and it fixed the problem. We were not able to find the cause of the problem and cannot afterwards. For any other people reading, please report any similar problems here.

**Comment by subhappy** [comment]
Seems I have the same problem, also running in Docker.

**Comment by subhappy** [comment]
I deleted the db to start over, and deleted a bunch of problematic files in the hopes of solving it.
But the problem still remains.
The thing is though, the files never get imported, just keep showing up in the library import and giving the message The volume that is desired to be added is already added.

So I can't do number 1 or 2, sorry. 

<img width="1572" height="618" alt="Image" src="https://github.com/user-attachments/assets/d66f0296-cbc7-4661-b258-ac2216e941bd" />

Here is a debug log though, during the import:
[Kapowarr_log_2026_01_08_12_12.txt](https://github.com/user-attachments/files/24494096/Kapowarr_log_2026_01_08_12_12.txt)

And here is the actual file, in the actual directory, not getting picked up by kapowarr even though the permissions are wide open:

> ubuntu@srvr% /mnt/space/comics/Preacher Special Cassidy  Blood and Whiskey/Volume 01 (1998) ls -l
total 22332
-rwxrwxrwx 1 ubuntu ubuntu 22865424 mars  23  2025 'Preacher Special: Cassidy : Blood and Whiskey #001 (1998).cbr'

**Comment by Casvt** [comment]
Mate... The file isn't matched to the volume. That makes the problem not the same as the one this issue is for at all. 

The file not matching to the volume after library import is a common problem. There's a FAQ topic just for it: [Why do files pop up in Library Import even though I just imported them?](https://casvt.github.io/Kapowarr/other_docs/faq/#why-do-files-pop-up-in-library-import-even-though-i-just-imported-them)

**Comment by subhappy** [comment]
Aah. This issue apparently outranked the faq in my search results. Sorry,
I'll RTFM.

Lars Augensen
(+47)40224293
