### ISSUE TITLE
Integrating the program with Homepage

### ISSUE THREAD

**Issue by Druidblack** [Casvt/Kapowarr#173]
![info](https://github.com/user-attachments/assets/236ed8f5-03d3-41d9-809f-569a3798e0cf)

Integrating Kapower into the [Homepage](https://gethomepage.dev/latest/) application using the application API.

     - Kapowarr:
        icon: kapowarr.png
        href: http://192.168.1.161:5656/
        description: Kapowarr is a software to build and manage a comic book library, fitting in the *arr suite of software.
        widget:
          type: customapi
          url: http://192.168.1.161:5656/api/volumes/stats?api_key=API
          refreshInterval: 10000 # 10 секунд
          method: GET
          mappings:
           - field: 
               result:
                  volumes
             label: Volumes
             format: number
           - field: 
               result:
                  issues
             label: Issues
             format: number
           - field: 
               result:
                  downloaded_issues
             label: Issues downloaded
             format: number
           - field: 
               result:
                  monitored
             label: Monitored
             format: number
           - field: 
               result:
                  total_file_size
             label: Total file size
             format: number

**Comment by Casvt** [comment]
What am I supposed to do with this?

**Comment by Druidblack** [comment]
You can close it as completed. In the description of the program, you can give a link to this. (if that suits you).  So that users can use your application in conjunction with the home page and other arr applications and get information from it.

**Comment by Casvt** [comment]
Maybe it's better for such a thing to be in the docs. Maybe there's a central place where such configs for softwares can be shared?

**Comment by Berserkir-Wolf** [comment]
I would suggest a 'guides' section in the docs, with companion software notes going in there.
