### ISSUE TITLE
Prevent Restricted/Problematic Characters in Filenames

### ISSUE THREAD

**Issue by dylan-k** [Casvt/Kapowarr#196]
There's an option to include `{issue_title}` when Kapowarr generates a filename, but this can result in filenames with restricted/problematic characters, for example if the title is `Chapter One Chosen; Sea Dogs Chapter Eight` this would put a semicolon in the filename.

While the semicolon isn't strictly probibited for filenames in every OS, it can be problematic in some contexts and should perhaps be avoided? Are filename variables scrubbed to prevent characters like these?

**Comment by Casvt** [comment]
There is a function in the code base just for the purpose of "cleaning" filenames, called `make_filename_safe()`, which simply uses the regex [`filename_cleaner`](https://github.com/Casvt/Kapowarr/blob/97957d1106924f473ab49e29f0113388090f0478/backend/naming.py#L64-L65) to remove invalid characters. Up to now there have been no problems reported for a semicolon being in the filename.

**Comment by dylan-k** [comment]
ok. sounds like this isn't really an issue then. Thanks for the explanation though :)
