### ISSUE TITLE
Feature Request: Add {issue_number} as a valuable for Volume Folder Naming

### ISSUE THREAD

**Issue by b3nd1k** [Casvt/Kapowarr#205]
For years I've been using [Audiobookshelf](https://www.audiobookshelf.org) to enjoying my ebooks and audiobooks, and it also works great with comics and mangas. Unfortunately, due to the limited options Kapowarr offers when it comes to volume _Volume Folder Naming_ the two services does not work great together. 

Adding `{issue_number}` as a variable for the _Volume Folder Naming_ would fix this. That would allow each issue to be placed in its own folder. 

**Audiobookshelf requires the following folder structure:**
```
-Author (Folder)
-- Book Folder (Folder)
--- eBook.pdf/epub/cbz
```

**Comment by Casvt** [comment]
Putting each issue in it's own folder is already possible. Just add a folder structure to the issue naming format.

E.g. a volume folder format of `{series_name}/Volume {volume_number}` and an issue naming format of `{series_name} Vol. {volume_number} Issue {issue_number}/book`. That gives a file like `Batman/Volume 2/Batman Vol. 2 Issue 3/book.cbz`.
