### ISSUE TITLE
Potential comic name processing issue?

### ISSUE THREAD

**Issue by rainrdx** [Casvt/Kapowarr#220]
**Description of the bug**

When I added G.I. Joe to the library, it fails to automatically download. If I choose manual search and choose to download G.I. Joe 2024 Issue 1, the download returns can't find download link. If I download the file and put in the import folder and choose import, the file will be identified in the scan, but won't be added to the library.

**To Reproduce**

Add G.I. Joe 2024 to the library

**Expected behaviour**

Automated download or import from scan.

**Screenshots**

There is no error message

**Version info**

Most recent docker

**Additional context**

**Comment by Casvt** [comment]
Edit the volume and override the Special Version to "Normal Volume".

The [FAQ](https://casvt.github.io/Kapowarr/other_docs/faq/#why-dont-my-files-match-to-the-volume) covers this topic (in your case, bullet 2 -> "Kapowarr is wrong" section).
