### ISSUE TITLE
Issue Number Padding

### ISSUE THREAD

**Issue by RevenantOne** [Casvt/Kapowarr#26]
**Is your feature request related to a problem? Please describe.**
There currently doesn't seem to be a way to format the issue numbering to allow the padding of zeroes.

**Describe the solution you'd like**
An option to specify a how much padding can be used in the naming of issues.
e.g. instead of `1, 2, 3, ..., 99, 100`
I'd like to be able to specify` 01, 02, 03, ..., 98, 99`
Or` 001, 002, 003, ..., 099, 100`

**Comment by Casvt** [comment]
Duplicate of #31
