### ISSUE TITLE
PUID and PGID support in container

### ISSUE THREAD

**Issue by jumpingmushroom** [Casvt/Kapowarr#33]
**Is your feature request related to a problem? Please describe.**
 I run your container on unraid from this contributed template (https://forums.unraid.net/topic/122788-support-jpdvm2014-templates/), but from what I can see there is no way to define which PUID and PGID the application within the container should run as, and so it seems to run as root by default. This causes some permission issues with newly created paths that are used by other applications with non-root permissions.

**Describe the solution you'd like**
A similar way that linuxserver.io does where you define PUID= and PGID= with unique ID's that the application runs as within the container. This would resolve the issue with files being written as root

**Comment by krtliv** [comment]
very much needed, as it is now the folders created are as root, i tried to set another puid and pgid and unfortunately kapowarr complains about the permissions.

**Comment by Berserkir-Wolf** [comment]
Defining the variables is being worked on, but making a dockerfile actually use them can be fun.
