### ISSUE TITLE
Delete volume and folder issues

### ISSUE THREAD

**Issue by jumpingmushroom** [Casvt/Kapowarr#34]
**Description of the bug**
When adding a volume, then trying to delete it causes an error:

> [2023-05-27 00:07:55][waitress-9][DEBUG] DELETE /api/volumes/34
> [2023-05-27 00:07:55][waitress-9][INFO] Deleting volume 34 with delete_folder set to True
> [2023-05-27 00:07:55][waitress-9][INFO] Deleting volume folder of 34
> [2023-05-27 00:07:55][waitress-9][ERROR] Exception on /api/volumes/34 [DELETE]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/app/frontend/api.py", line 54, in wrapper
>     return method(*args, **kwargs)
>   File "/app/frontend/api.py", line 174, in wrapper
>     result = method(*args, **kwargs)
>   File "/app/frontend/api.py", line 401, in api_volume
>     volume.delete(delete_folder=delete_folder)
>   File "/app/backend/volumes.py", line 300, in delete
>     delete_volume_folder(self.id)
>   File "/app/backend/files.py", line 534, in delete_volume_folder
>     samefile(folder, root_folder)
>   File "/usr/local/lib/python3.8/genericpath.py", line 100, in samefile
>     s1 = os.stat(f1)
> FileNotFoundError: [Errno 2] No such file or directory: '/content/DC Comics/Watchmen (1986)'

The path gets deleted, but it seems to do an extra check somewhere that causes it to no longer find it.

**To Reproduce**

1. Add tWatchmen (1986)
2. Delete and select yes to delete the folder
3. Same error repeats if trying to click delete again
4. Selecting no causes the volume to be removed from the database and ends up being a successful removal of both database item as well as folder

**Expected behaviour**
Both folder and volume gets removed from the database and filesystem

**Version info**
Kapowarr: v1.0.0-beta-1
Python: 3.8.16.final.0
Database version: 6

Happens both on Windows 11 with google chrome version 113.0.5672.127 and on Ubuntu 22.04 with the same chrome version. Not tested on other browsers, yet.

**Comment by Casvt** [comment]
Do you have only one folder between the root folder and the content? E.g. `/rootfolder/Watchmen (1986)/Issue 1.cbr`. 

Because if so, then the error will have been fixed already in commit e2876c8b8bc48d7035f904a9848dd296d9273e05. Two bugs, fixed with one commit.

**Comment by Casvt** [comment]
@jumpingmushroom Please respond

**Comment by Casvt** [comment]
@jumpingmushroom I'm going to close the issue until you respond.
