### ISSUE TITLE
Year as volume number

### ISSUE THREAD

**Issue by Fabaderheld** [Casvt/Kapowarr#37]
**Description of the bug**
Downloaded files are not added to db after being downloaded.  The files are named correctly in the root folder, but aren't picked up

**To Reproduce**
1. Go to settings
2. Go to media management
3. Change file naming to 
~~~
{series_name} Vol.{year} - #{issue_number} ({issue_release_date})
~~~

**Expected behaviour**
File added to db after download

**Version info**
v1.0.0-beta-1
Chrome 113.0.5672.127 on Windows 11 (22621.1105)

**Additional context**

**Comment by Casvt** [comment]
The year as the volume number isn't handled well yet. That's the problem.
