### ISSUE TITLE
cant install using portainer

### ISSUE THREAD

**Issue by mareczek82** [Casvt/Kapowarr#47]
**Description of the bug**
information from portainer 
*failed to deploy a stack: service "kapowarr" refers to undefined volume kapowarr-db: invalid compose project*

**To Reproduce**
I just copied compose scheme and paste it to painteiner, i changed only paths to download and root folders

**Comment by Berserkir-Wolf** [comment]
Ah, right - if you do this with a named volume (`- 'kapowarr-db:/app/db'`) then it has to exist prior to starting the container.
To make it in portainer:
- Open `Volumes`
- Click `Add Volume`
- Enter name matching the one you'll use in compose (`kapowarr-db`)
- Click `Create the volume`
- Open `Stacks`
- Create the stack with the named volume in it.

**Comment by Berserkir-Wolf** [comment]
Added this to docs for future enquiries, in PR #49

**Comment by mareczek82** [comment]
It didnt help. 
I followed those steps, made volume but I still have same problem

**Comment by Berserkir-Wolf** [comment]
If you look at the volumes page in portainer after creating the volume, can you see the new one there?
I've seen portainer throw errors when the UI for it is cached in your browser (like the site knew the volume didn't exist, so it won't even check with the docker engine to see if that's changed). Pressing `ctrl + f5` _should_ clear your browser cache and reload it fresh.

Once that's cleared, confirm the volume still exists (create it if it doesn't), then go to stacks and create it fresh. Don't do it across multiple tabs, the cache _will_ start to pollute between them.
