### ISSUE TITLE
Contribution Request: manual installation instructions for Ubuntu

### ISSUE THREAD

**Issue by RationalAnarchist** [Casvt/Kapowarr#57]
I have taken note of the steps needed to install Kapowarr on Ubuntu - would like to contribute to the installation instructions page, if that would be useful.  If there are specific distros that you'd like me to validate instructions for, let me know - I can spin them up in azure and figure it out.

**Comment by Casvt** [comment]
Sounds good. Go ahead.

**Comment by Berserkir-Wolf** [comment]
I'll write up a page on how to submit PRs etc for the docs at some point soon (possibly this weekend), just to allow for any future queries. Possibly a "how to contribute to the code/docs" page in general.
