### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by kleivadas** [Casvt/Kapowarr#58]
![Screenshot 2023-06-14 at 12 49 36 AM](https://github.com/Casvt/Kapowarr/assets/136313260/608e2576-d505-411a-9bf4-8087bdb55558)
**Description of the bug**
Added multiple Volumes (comics) and suddenly Kapowarr froze at the state "Updating Info of all volumes" and was unable to complete. While the Activity - Queue was downloading some missing comics and stuck at "Importing".

By checking the logs i see "OperationalError: database is locked".

**To Reproduce**
1. Add multiple volumes of various comics
2. Search monitored
3. Restart Kapowar

**Additional context**

I'm not familiar with Python but by searching on the Internet about concurrency for sqlite i found this 
**"PRAGMA journal_mode = wal;"**

```
super().__init__(self.file, timeout=timeout)
super().cursor().execute("PRAGMA foreign_keys = ON;")
super().cursor().execute("PRAGMA journal_mode = wal;")
return
```

adding this line of code to db.py seems that it fixed this. I managed to see all volumes again and "db locked" message is not appearing anymore.

**Comment by Casvt** [comment]
I tried this first on [MIND](https://github.com/Casvt/MIND). Your simple fix of adding the one line `super().cursor().execute("PRAGMA journal_mode = wal;")` is indeed a _good start_, but for the journal mode to be set to WAL requires more "handling" to properly use it.

In [this](https://github.com/Casvt/MIND/commit/8c5e34caee26a7cf79731d690f6c972978b8f80d) commit to MIND, I've implemented WAL journal mode. Most important part of the commit is [this expansion on a waitress class](https://github.com/Casvt/MIND/commit/8c5e34caee26a7cf79731d690f6c972978b8f80d#diff-bc8a07b30311c3855f97fa6c91d417c45bff44e488287052cda4bba86848a585R26), which makes sure that the database connections get closed properly, avoiding the temporary database files generated by the WAL mode in the folder while MIND/Kapowarr is not running.

So it required a bit more code than you suggested, but setting the journal mode to WAL indeed was the way to go, and I'll be making the same changes to Kapowarr too.
