### ISSUE TITLE
Number issues set number of leading zeros

### ISSUE THREAD

**Issue by rgecko** [Casvt/Kapowarr#61]
**Is your feature request related to a problem? Please describe.**
when configuring file renaming, you should be able to set the number of zero's before the first number, for example issue number one should be "comic name 1" or "comic name 001" when you get to issue ten it would be "comic name 010"

**Describe the solution you'd like**
the ability to set leading zeros in file renaming so {issue_number} can have a parameter in it like {issue_number-000} to determine how many zeros to pad with.

**Additional context**

**Comment by Casvt** [comment]
Already added in PR #38
