### ISSUE TITLE
Can't search Add Volume using numpad enter

### ISSUE THREAD

**Issue by ngInit** [Casvt/Kapowarr#65]
**Description of the bug**
You have to hit enter to search on the Add Volume page, and this doesn't work with the numpad.

**To Reproduce**
1. Go to Volumes > Add Volume
2. Type in a comic name
3. Hit enter on the numpad - nothing happens
4. Hit enter using the main enter key - it searches as expected

**Expected behaviour**
The numpad enter key should work the same as the regular enter key.

**Version info**
Kapowarr version	v1.0.0-beta-1
Python version	3.8.16.final.0
Database version	6

**Comment by Berserkir-Wolf** [comment]
Doesn't work with mobile browser keyboard either.
