### ISSUE TITLE
Add issue year variable to File Naming

### ISSUE THREAD

**Issue by ngInit** [Casvt/Kapowarr#66]
**Is your feature request related to a problem? Please describe.**
There's no way to add the issue release year to an issue in `Settings > Media Management > File Naming`

**Describe the solution you'd like**
Currently we have `{year}` and `{issue_release_date}`. There are a couple of solutions...

1. Change `{year}` to be `{volume_year}`, and add an `{issue_release_year}` variable
2. Just add an `{issue_release_year}` variable
3. Change `{year}` to be the issue year when used in File Naming

**Comment by Casvt** [comment]
I think I'll go with the second option. Won't be very hard to add.
