### ISSUE TITLE
(Automatic) File conversion

### ISSUE THREAD

**Issue by Casvt** [Casvt/Kapowarr#67]
**Is your feature request related to a problem? Please describe.**

The format that the file is in supplied is also the final format on the drive.

**Describe the solution you'd like**

The ability to convert between file formats (e.g. try to convert all files to CBR if possible). It should also be possible to automatically do this when importing downloaded files. As many conversion directions should be added as possible.

**Additional context**

There are loads of scripts on GitHub for individual type-to-type conversions. Basically find a script for each type of conversion and combine them all.

**Comment by Berserkir-Wolf** [comment]
I'd say an option for CBZ conversion would be pretty nice - especially given CBZ supports archive tagging for metadata (which would then tie in with #50 pretty nicely, as it would mean an issue could be converted to CBZ and have the metadata embedded in the archive tags).

**Comment by Berserkir-Wolf** [comment]
Using something like [oogg06/cbr2cbz](https://github.com/oogg06/cbr2cbz) could be a good starting point for the conversion side
