### ISSUE TITLE
Manga support

### ISSUE THREAD

**Issue by bl4ckph0en1x** [Casvt/Kapowarr#73]
**Is your feature request related to a problem? Please describe.**

As long as Kapowarr only supports GetComics for downloading it will only be able to handle comics and not manga's. The last are not available on the site. I suppose many are collecting manga and not only comics.

**Describe the solution you'd like**

Support other downloads methods: torrents or NZB. Either should be fine
Would it be possible to use the same scraper used on getcomics on jnovels.com/

**Additional context**

Other download methods should be prioritized as this will add several new sources and allow to handle manga.

**Comment by Casvt** [comment]
You're basically asking for indexer and torrent support. There are already issues for that.
