### ISSUE TITLE
Add support to League of Comic Geeks

### ISSUE THREAD

**Issue by opicron** [Casvt/Kapowarr#75]
**Is your feature request related to a problem? Please describe.**
I manage my library through League of Comic Geeks.
Import volumes through League of Comic Geeks, or its export, would save time by avoiding to add all volumes manually.

**Describe the solution you'd like**
Ability to import the export of League of Comic Geeks
or
Ability to import directly from League of Comic Geeks
or 
Import GC subscriptions

**Comment by therobbiedavis** [comment]
We looked into implementing support for LoCG for Kavita, but there is no officially supported API and they are not looking to implement one anytime soon. https://leagueofcomicgeeks.uservoice.com/forums/213333-feature-requests/suggestions/6893699-api-access

**Comment by opicron** [comment]
As long as there is no API this is not possible. Please close this issue ;).
