### ISSUE TITLE
Add support for x_forwarded_for

### ISSUE THREAD

**Issue by Berserkir-Wolf** [Casvt/Kapowarr#80]
**Is your feature request related to a problem? Please describe.**
When using a reverse proxy, kapowarr logs all requests as coming from the proxy.  
`2023-07-24T04:29:16.314292000Z [2023-07-24 16:29:16][waitress-0][INFO] Login attempt successful from 192.168.10.21`

**Describe the solution you'd like**
I'd like an option in settings to enable reverse proxy support.  
Enabling this could then activate the option for a baseurl (since that's pretty much the only reason to use one), and set the server process to listen for the `x_forwarded_for` header, which would pass information through so that the log would show the login attempt source correctly (provided the proxy is setting it correctly).

**Comment by Casvt** [comment]
I've never used proxies so I don't have much experience with them (I barely know how they even work). Searching StackOverflow, all solutions search for the `HTTP_X_FORWARDED_FOR` header. Is that the same as the `X_FORWARDED_FOR` header you give? Or would I need to check for both headers? How many "variances" are there of this header that I should be searching for?

**Comment by Berserkir-Wolf** [comment]
`HTTP_X_FORWARDED_FOR` is the proper name for it - should be using that.
