### ISSUE TITLE
Add docs for setting permissions of database folder

### ISSUE THREAD

**Issue by Casvt** [Casvt/Kapowarr#84]
**Is your feature request related to a problem? Please describe.**

Had someone on the discord server having problems with setting up Kapowarr using a normal folder for the database file instead of a docker volume (at `/opt/kapowarr/db`). Turned out that the folder was owned by root, which lead to errors when starting up the container because it wasn't run using root.

**Describe the solution you'd like**

There should be more documentation on setting ownership and permissions of the database folder when going that route.

**Additional context**

**Comment by Berserkir-Wolf** [comment]
I'd say this should go in FAQ.

What permission do you recommend for the folder? I've started a branch adding this in, just wanting to double check.

**Comment by Casvt** [comment]
It can go in the FAQ but there will need to be a link to it in the installation instructions at the part for adding a folder. 

For the permissions I would set the folder to 770. And ownership to the user that also runs the docker containers (most often user 1000).
