### ISSUE TITLE
Unwanted space is added to folder of series

### ISSUE THREAD

**Issue by opicron** [Casvt/Kapowarr#89]
**Description of the bug**
A space is being added to one of my series. See screenhot. Even when I remove the space and save the new path, the space is added again. While other volume of this series do not have a space added.

**To Reproduce**

Add Alien volume 3 from 2023.

**Expected behaviour**
1) The space should not be added when adding the series
2) When manually adjusting the path it should be saved*1

*1 It seems no changes are saved to folder path, no matter what I type-- it reverts back to the old value.

**Screenshots**
![image](https://github.com/Casvt/Kapowarr/assets/472432/24734024-3628-4df9-a7fe-5de4ee2a71e5)
![image](https://github.com/Casvt/Kapowarr/assets/472432/2d61e6d2-2dde-45d6-8906-f928ce294e1b)

**Comment by Casvt** [comment]
Seems like the metadata from comicvine has the space at the end. But I could add a line to remove any spaces at the beginning or the end no problem.

**Comment by opicron** [comment]
Thanks! But is it correct that the path can not be changed manually?

**Comment by Casvt** [comment]
The volume folder? Yes it can. In the screenshots that you shared, at "Volume Folder", you can enter any folder (or even a folder tree) that should become the volume folder and click "Update" to save. Kapowarr will move everything to the newly set folder and use that as the folder from then on. If a custom folder is set, Kapowarr will never change the name of the folder.

**Comment by opicron** [comment]
I will try again, Im fairly positive the new folder does not get saved.

**Comment by Casvt** [comment]
I have added code to remove these type of spaces from the title, so that'll be included in the next release. I tried changing the volume folder (without the new code), where I change `Alien /Volume 3 (2023)` to `Alien/Volume 3 (2023)`, and it worked.
