### ISSUE TITLE
Windows installer request

### ISSUE THREAD

**Issue by JohnKFisher** [Casvt/Kapowarr#97]
**Is your feature request related to a problem? Please describe.**
Would like Windows installer like sonarr, to avoid need of docker, etc configuration

**Describe the solution you'd like**
I mean, a Windows installer. :-)

**Additional context**
Obviously this may not be priority as the entire app is still in beta, just putting the request out there.

**Comment by Berserkir-Wolf** [comment]
Given that the application runs on Python, you can download the release file and run the relevant file with Python directly. 
This is an unsupported method, but it does work.

**Comment by Casvt** [comment]
> and run the relevant file with Python directly.

\* After installing the requirements.

> This is an unsupported method, but it does work.

It _is_ supported. I just don't advice it because you have to manually set up the requirements, updating and permissions, while docker takes care of all that for you.

**Comment by Casvt** [comment]
When you use docker, the only thing you have to do is run one or two commands. The configuration required can't be simplified using an installer of some sorts. Basically, it's already as easy and simple as possible to install it.

When you want to run it directly on Windows, I guess a script could be made to create a folder, automatically clone the repo to it, install the dependencies and set up NSSM. There is a platform/website/repo that creates installation scripts for these *arrs and relevant softwares, but I forgot what their name was. You could ask them to create one for Kapowarr. @Berserkir-Wolf probably knows the name.

**Comment by Berserkir-Wolf** [comment]
I do not know, unfortunately.

**Comment by Casvt** [comment]
I remembered: TraSH Guides

https://trash-guides.info/
