### ISSUE TITLE
Feature Request: For tracking of Volume on front page show {issues in system}/{issues monitored} rather than {issues in system}/{issues in volume}

### ISSUE THREAD

**Issue by JaredVanderford** [Casvt/Kapowarr#98]
**Is your feature request related to a problem? Please describe.**
The front page is a good way to track what issues I'm missing for those volumes I have all issues of.  However I like to clean up my books over time so I don't have a bunch of space wasted by books I won't read again.  Right now even if I don't monitor all issues in a volume, the completion bar and number show as missing all those issues I've marked as not monitored.  This makes it hard to tell when new issues are missing vs old issues I don't want to have.

**Describe the solution you'd like**
Simply use the issues monitored for the lower number and what issues are present and monitored for the upper number.

**Comment by Casvt** [comment]
See "Superman: Lost" in the image below (click on image to enlarge). Issue 7 is not downloaded.

If all issues are monitored (top right), the bar is 6/7 (top left). If issue 7 is unmonitored (bottom right), the bar is 6/6 (bottom left).

![image](https://github.com/Casvt/Kapowarr/assets/88994465/9bba763e-1276-4c3d-896c-99287acf106e)
